### ISSUE TITLE
Pull to Refresh

### ISSUE THREAD

**Issue by mikaelacaron** [mikaelacaron/brain-marks#65]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
* Add pull to refresh on the categories screen
   * Refresh the categories from AWS Amplify DataStore
* Add pull to refresh on the tweets screen
   * Fetch all tweets for the certain category from the Twitter API

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by haIIux** [comment]
Could you please assign this to me? I am going to make an attempt on this! Only thing I'm wondering is if this feature is truly necessary since the application updates automatically every time you add a Tweet or Category.

**Comment by haIIux** [comment]
Interesting, when I used the simulator and added a Category, it immediately added it to the list. Additionally in the simulator, when I added a Tweet to a category it added right away. Regardless, I will try to determine the most appropriate method to implement this feature. I have one roughed out and I believe it works, just need to figure out how to test it properly since I'm not having an issue lol

**Comment by haIIux** [comment]
https://user-images.githubusercontent.com/47156971/136305975-4cb6eb0b-3594-44ab-8313-50752c6c9300.mp4

Current rendition. I need to figure out how to properly get the `emptyView()` properly centered again.
